// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLfIMQRg7MAwWswzw8auv8BSNDh7mQy58',
    appId: '1:498514146362:web:04f3bd6ab6bff26688b103',
    messagingSenderId: '498514146362',
    projectId: 'lbs9dkiawtik',
    authDomain: 'lbs9dkiawtik.firebaseapp.com',
    storageBucket: 'lbs9dkiawtik.firebasestorage.app',
    measurementId: 'G-2CP5KN4ZD9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAExboJsGBtbBAPozWPbaOQxdh8Mr-8SWE',
    appId: '1:498514146362:ios:bd81a37ebc8bba8288b103',
    messagingSenderId: '498514146362',
    projectId: 'lbs9dkiawtik',
    storageBucket: 'lbs9dkiawtik.firebasestorage.app',
    iosBundleId: 'com.example.lbs9dkiwatik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAExboJsGBtbBAPozWPbaOQxdh8Mr-8SWE',
    appId: '1:498514146362:ios:bd81a37ebc8bba8288b103',
    messagingSenderId: '498514146362',
    projectId: 'lbs9dkiawtik',
    storageBucket: 'lbs9dkiawtik.firebasestorage.app',
    iosBundleId: 'com.example.lbs9dkiwatik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLfIMQRg7MAwWswzw8auv8BSNDh7mQy58',
    appId: '1:498514146362:web:3b67286e49b8b50088b103',
    messagingSenderId: '498514146362',
    projectId: 'lbs9dkiawtik',
    authDomain: 'lbs9dkiawtik.firebaseapp.com',
    storageBucket: 'lbs9dkiawtik.firebasestorage.app',
    measurementId: 'G-LNGFPS7BMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArZJDRXA56h52H7uPLYyAnpPDILhon8M',
    appId: '1:498514146362:android:331805d81202fd2c88b103',
    messagingSenderId: '498514146362',
    projectId: 'lbs9dkiawtik',
    storageBucket: 'lbs9dkiawtik.firebasestorage.app',
  );

}